### ISSUE TITLE
Dockerfile for sysbox-install and crio-install images

### ISSUE THREAD

**Issue by mojojoji** [nestybox/sysbox-pods-preview#6]
Where can i find the Dockerfile used to build the images `registry.nestybox.com/nestybox/sysbox-deploy-k8s` and `registry.nestybox.com/nestybox/crio-deploy-k8s`? Can those be added to this repo?

**Comment by ctalledo** [comment]
Hi @mojojoji ,

That Dockerfile and related scripts are part of the sysbox packaging repo which is currently private to Nestybox. Also, in order to generate the container image for sysbox-deploy-k8s, I have to first build the Sysbox binaries for the supported distros and preload them into that container, so it's a bit of a manual process now.

Curious, is there any thing you are looking to change/add to the sysbox-deploy-k8s image?

**Comment by mojojoji** [comment]
I was trying it out in Google Kubernetes engine with Ubuntu containerd nodes and kubernetes version of 1.20. The node images did not have rsync and shiftfs. I had to manually install these in the nodes to get sysbox pods working.

I was thinking of adding rsync and shiftfs installation to the install script that was inside the sysbox install container so that everything required in the nodes are setup by the daemonsets.

**Comment by ctalledo** [comment]
Hi @mojojoji,

> I was trying it out in Google Kubernetes engine with Ubuntu containerd nodes and kubernetes version of 1.20. The node images did not have rsync and shiftfs. I had to manually install these in the nodes to get sysbox pods working.

That's great, glad to hear you got it working; GKE is still a work in progress for us (since it does not support CRI-O natively), but with the daemonsets it's possible to get it to work (although some GKE daemonsets don't seem to like CRI-O for some reason).

> I was thinking of adding rsync and shiftfs installation to the install script that was inside the sysbox install container so that everything required in the nodes are setup by the daemonsets.

That's exactly what I am working on right now :) 

I hope to have something ready tomorrow or by the weekend. Ideally the daemonsets take care of all host setup, so no extra setup is required by users. 

Glad to know we are thinking along the same lines :)

**Comment by ctalledo** [comment]
Hi @mojojoji,

I've updated the sysbox-deploy-k8s daemonset to install all sysbox dependencies on the k8s worker node (e.g., shiftfs, rsync, etc). 

With this change, no manual config on the k8s worker node should be required prior to installing sysbox.

Please give it a shot and let me know how it goes.

Thanks!

**Comment by ctalledo** [comment]
Closing this issue as the requested task is now complete.
